import React from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { jsPDF } from "jspdf";

export function exportEasyStepsPDF(taskTitle, steps) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(30, 30, 30);
  const titleLines = doc.splitTextToSize(taskTitle, contentWidth - 10);
  doc.text(titleLines, margin, 28);

  // Divider line
  const titleBlockHeight = titleLines.length * 9;
  const dividerY = 28 + titleBlockHeight + 4;
  doc.setDrawColor(180, 160, 220);
  doc.setLineWidth(0.6);
  doc.line(margin, dividerY, pageWidth - margin, dividerY);

  // Steps
  let y = dividerY + 12;
  const stepSpacing = 18;
  const circleRadius = 4.5;

  steps.forEach((step, index) => {
    if (y > pageHeight - 30) {
      doc.addPage();
      y = 20;
    }

    // Checkbox circle
    doc.setDrawColor(140, 100, 210);
    doc.setLineWidth(0.8);
    doc.circle(margin + circleRadius, y - 1.5, circleRadius);

    // Step number inside circle
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(140, 100, 210);
    const numStr = String(index + 1);
    const numX = margin + circleRadius - (numStr.length > 1 ? 2.5 : 1.5);
    doc.text(numStr, numX, y + 1.2);

    // Step title
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    const stepText = step.title || step;
    const textX = margin + circleRadius * 2 + 4;
    const wrappedText = doc.splitTextToSize(stepText, contentWidth - circleRadius * 2 - 6);
    doc.text(wrappedText, textX, y + 1.2);

    // Time estimate if available
    if (step.estimated_minutes) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(140, 140, 140);
      const extraY = y + wrappedText.length * 5.5;
      doc.text(`~${step.estimated_minutes} min`, textX, extraY);
      y += wrappedText.length * 5.5 + stepSpacing;
    } else {
      y += wrappedText.length * 5.5 + stepSpacing;
    }
  });

  // Footer
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, pageHeight - 16, pageWidth - margin, pageHeight - 16);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 160);
  doc.text("Generated by TaskBuddy — taskbuddyapp.com.au", pageWidth / 2, pageHeight - 9, { align: "center" });

  // Save
  const safeTitle = taskTitle.replace(/[^a-z0-9]/gi, "_").substring(0, 40);
  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`EasySteps_${safeTitle}_${dateStr}.pdf`);
}

export default function ExportEasyStepsButton({ taskTitle, steps, className = "" }) {
  if (!steps || steps.length === 0) return null;

  return (
    <Button
      variant="outline"
      onClick={() => exportEasyStepsPDF(taskTitle, steps)}
      className={`border-purple-200 text-purple-700 hover:bg-purple-50 ${className}`}
    >
      <Download className="w-4 h-4 mr-2" />
      Export as Easy Steps
    </Button>
  );
}