import React from "react";
import { Button } from "@/components/ui/button";
import { FileText, Download } from "lucide-react";
import { format } from "date-fns";
import { jsPDF } from "jspdf";

function exportReportPDF(report) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 20;

  const purple = [139, 92, 246];
  const dark = [17, 24, 39];
  const grey = [107, 114, 128];

  const addFooter = () => {
    const pageH = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(...grey);
    doc.text("Generated by TaskBuddy — taskbuddyapp.online", margin, pageH - 12);
    doc.setFont(undefined, "italic");
    doc.text(
      "This report was generated using assistive technology usage data and is intended to support NDIS plan reviews and progress notes.",
      margin, pageH - 7, { maxWidth: contentW }
    );
    doc.setFont(undefined, "normal");
  };

  const checkPageBreak = (neededHeight = 10) => {
    const pageH = doc.internal.pageSize.getHeight();
    if (y + neededHeight > pageH - 25) {
      addFooter();
      doc.addPage();
      y = 20;
    }
  };

  const divider = () => {
    checkPageBreak(6);
    doc.setDrawColor(...grey);
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageW - margin, y);
    y += 6;
  };

  // Header
  doc.setFontSize(18);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...purple);
  doc.text("TaskBuddy", margin, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont(undefined, "normal");
  doc.setTextColor(...grey);
  doc.text("Clinical Progress Report", margin, y);
  y += 8;

  divider();

  // Report details
  const labelValue = (label, value) => {
    checkPageBreak(7);
    doc.setFontSize(10);
    doc.setTextColor(...grey);
    doc.setFont(undefined, "normal");
    doc.text(`${label} `, margin, y);
    doc.setTextColor(...dark);
    doc.setFont(undefined, "bold");
    const labelWidth = doc.getTextWidth(`${label} `);
    doc.text(value || "—", margin + labelWidth, y);
    doc.setFont(undefined, "normal");
    y += 7;
  };

  labelValue("Client:", report.client_display_name || "—");

  const periodStart = report.report_period_start
    ? format(new Date(report.report_period_start), "dd/MM/yyyy") : "—";
  const periodEnd = report.report_period_end
    ? format(new Date(report.report_period_end), "dd/MM/yyyy") : "—";
  labelValue("Report Period:", `${periodStart} to ${periodEnd}`);

  const genDate = report.generated_date
    ? format(new Date(report.generated_date), "dd/MM/yyyy") : "—";
  labelValue("Generated:", genDate);
  labelValue("Support Type:", report.support_type || "—");

  divider();

  // Progress metrics
  checkPageBreak(10);
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...purple);
  doc.text("Progress Summary", margin, y);
  y += 8;

  const metric = (label, value) => {
    checkPageBreak(7);
    doc.setFontSize(10);
    doc.setTextColor(...grey);
    doc.setFont(undefined, "normal");
    doc.text(`${label} `, margin, y);
    doc.setTextColor(...dark);
    const lw = doc.getTextWidth(`${label} `);
    doc.text(String(value ?? "—"), margin + lw, y);
    y += 7;
  };

  metric("Tasks Initiated:", report.tasks_initiated ?? "—");
  metric("Tasks Completed:", report.tasks_completed ?? "—");
  metric("Completion Rate:", report.completion_rate != null ? `${report.completion_rate}%` : "—");
  metric("Current Streak:", report.current_streak != null ? `${report.current_streak} days` : "—");
  metric("Best Time of Day:", report.best_time_of_day || "—");

  divider();

  // Goal section
  checkPageBreak(10);
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...purple);
  doc.text("Support Goal", margin, y);
  y += 8;

  if (report.goal_description) {
    doc.setFontSize(10);
    doc.setFont(undefined, "normal");
    doc.setTextColor(...dark);
    const goalLines = doc.splitTextToSize(report.goal_description, contentW);
    goalLines.forEach(line => {
      checkPageBreak(7);
      doc.text(line, margin, y);
      y += 6;
    });
  } else {
    doc.setFontSize(10);
    doc.setTextColor(...grey);
    doc.text("No goal description provided.", margin, y);
    y += 6;
  }

  divider();

  // Narrative section
  checkPageBreak(10);
  doc.setFontSize(11);
  doc.setFont(undefined, "bold");
  doc.setTextColor(...purple);
  doc.text("Clinician Narrative", margin, y);
  y += 8;

  if (report.narrative_summary) {
    doc.setFontSize(10);
    doc.setFont(undefined, "normal");
    doc.setTextColor(...dark);
    const narLines = doc.splitTextToSize(report.narrative_summary, contentW);
    narLines.forEach(line => {
      checkPageBreak(7);
      doc.text(line, margin, y);
      y += 6;
    });
  } else {
    doc.setFontSize(10);
    doc.setTextColor(...grey);
    doc.text("No narrative summary available.", margin, y);
    y += 6;
  }

  addFooter();

  const clientName = (report.client_display_name || "Client").replace(/\s+/g, "_");
  const endDate = report.report_period_end
    ? format(new Date(report.report_period_end), "yyyy-MM-dd") : "unknown";
  doc.save(`TaskBuddy_Report_${clientName}_${endDate}.pdf`);
}

export default function ClinicianReportsList({ reports }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">Recent Reports</h2>

      {reports.length === 0 ? (
        <div className="rounded-2xl border border-dashed border-gray-200 dark:border-gray-700 p-10 text-center bg-white/50 dark:bg-white/5">
          <FileText className="w-8 h-8 mx-auto text-gray-300 dark:text-gray-600 mb-3" />
          <p className="text-gray-500 dark:text-gray-400 text-sm">No reports generated yet</p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map((report) => (
            <div
              key={report.id}
              className="rounded-2xl bg-white/70 dark:bg-white/5 border border-purple-100 dark:border-purple-900/40 p-4"
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0 space-y-1">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className="font-semibold text-gray-900 dark:text-gray-100 text-sm">
                      {report.client_display_name || "Client"}
                    </p>
                    {report.generated_date && (
                      <span className="text-xs text-gray-400 dark:text-gray-500">
                        {format(new Date(report.generated_date), "d MMM yyyy")}
                      </span>
                    )}
                    {report.report_period_start && report.report_period_end && (
                      <span className="text-xs bg-gray-100 dark:bg-gray-800 text-gray-500 dark:text-gray-400 px-2 py-0.5 rounded-full">
                        {format(new Date(report.report_period_start), "d MMM")} – {format(new Date(report.report_period_end), "d MMM yyyy")}
                      </span>
                    )}
                    {report.completion_rate != null && (
                      <span className="text-xs bg-teal-100 dark:bg-teal-900/30 text-teal-700 dark:text-teal-400 font-medium px-2 py-0.5 rounded-full">
                        {report.completion_rate}% completion
                      </span>
                    )}
                  </div>
                  {report.narrative_summary && (
                    <p className="text-xs text-gray-600 dark:text-gray-400 line-clamp-3 leading-relaxed">
                      {report.narrative_summary}
                    </p>
                  )}
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  className="shrink-0 border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 text-xs"
                  onClick={() => exportReportPDF(report)}
                >
                  <Download className="w-3 h-3 mr-1" />
                  PDF
                </Button>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}